[package]
name = "sbor"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto-bigint = { version = "0.5.0", default-features = false }
staticvec = { version = "0.11.9", default-features = false }
paste = "1.0.9"