name: BabylonLedgerApp

on:
  push:
    branches:
      master
  pull_request:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manually triggered'

env:
  CARGO_TERM_COLOR: always
  NODE_TLS_REJECT_UNAUTHORIZED: 0

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchains
        uses: RDXWorks-actions/toolchain@master
        with:
          toolchain: nightly-2023-05-28
          override: true
          components: rust-src, rustfmt
      - uses: RDXWorks-actions/checkout@main
      - name: Cargo fmt
        uses: RDXWorks-actions/cargo@master
        with:
          command: fmt
          args: --all -- --check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchains
        uses: RDXWorks-actions/toolchain@master
        with:
          toolchain: nightly-2023-05-28
          override: true
          components: rust-src
      - uses: RDXWorks-actions/checkout@main
      - name: Unit tests
        run: |
          rm -rf .cargo
          cd sbor
          cargo test
